import React from 'react'
import Head from 'next/head'
import Navbar from '../components/navbar'
import HomePage from './homePage'
import Skills from './skills'
import Work from './work'
import Footer from '../components/Footer'
export default function Home() {
  return (
    <div>
       <Head>

       </Head>
       <Navbar />
       <HomePage />
       <Skills />
       <Work />
       <Footer />
    </div>
    // <div className={styles.container}>
    //     <title>Portfolio</title>
    //   <Head>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //   <navbar />
    //   <main className={styles.main}>
    //     <div className="">
    //       <h2>Hello, I am</h2>
    //       <h1>Wonjune Jung,</h1>
    //       <h1>Software Developer</h1>
    //     </div>
    //     <div>
    //       <Image 
    //       src='/hi.png'
    //       alt='hi'
    //       width={500}
    //       height={500}
    //       />
    //     </div>
    //   </main>
    // </div>
  )
}
