import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="">
          <h2>Hello, I am</h2>
          <h1>Wonjune Jung,</h1>
          <h1>Software Developer</h1>
        </div>
        <div>
          <Image 
          src='/hi.png'
          alt='hi'
          width={500}
          height={500}
          />
        </div>
      </main>
    </div>
  )
}
